theme: jekyll-theme-slate
title: Los pros de Robotik 2022-1
description: Página web para el desarrollo del proyecto final de Robótica de la Universidad Nacional de Colombia 2022-1 en el proyecto C1/C2/A2
